package org.eleria.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utilisateurs generated by hbm2java
 */

@Entity
@Table(name="utilisateurs")
public class utilisateurs implements java.io.Serializable {

	@Id
	@Column(name="ID")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	private String nom;
	private String prenom;
	private String login;
	@Column(name="mot_de_passe")
	private String motDePasse;
	private int societe;
	private String email;
	private int type;
	private String portable_pro;
	private String portable_perso;
	private String adresse1;
	private String adresse2;
	private String code_postal;
	private String ville;
	private String genre;
	
	public String getGenre() {
		return genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	public String getPortable_pro() {
		return portable_pro;
	}

	public void setPortable_pro(String portable_pro) {
		this.portable_pro = portable_pro;
	}

	public String getPortable_perso() {
		return portable_perso;
	}

	public void setPortable_perso(String portable_perso) {
		this.portable_perso = portable_perso;
	}

	public String getAdresse1() {
		return adresse1;
	}

	public void setAdresse1(String adresse1) {
		this.adresse1 = adresse1;
	}

	public String getAdresse2() {
		return adresse2;
	}

	public void setAdresse2(String adresse2) {
		this.adresse2 = adresse2;
	}

	public String getCode_postal() {
		return code_postal;
	}

	public void setCode_postal(String code_postal) {
		this.code_postal = code_postal;
	}

	public String getVille() {
		return ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public utilisateurs() {
	}

	public utilisateurs(int id, String nom, String prenom, String login,
			String motDePasse, int societe, String email, int type) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.motDePasse = motDePasse;
		this.societe = societe;
		this.email = email;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	public int getSociete() {
		return this.societe;
	}

	public void setSociete(int societe) {
		this.societe = societe;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}
}
